// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDol-mM_GALl7VPmjyAg5Ntw5adz9DA6w8',
    appId: '1:70017366922:web:603ce575df41817dcca673',
    messagingSenderId: '70017366922',
    projectId: 'dictojtapp',
    authDomain: 'dictojtapp.firebaseapp.com',
    storageBucket: 'dictojtapp.firebasestorage.app',
    measurementId: 'G-2TQP0Y9KN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZtW41F2AnqeICh-CrX14QJ8uIqxTDK6w',
    appId: '1:70017366922:android:826fabc679e46269cca673',
    messagingSenderId: '70017366922',
    projectId: 'dictojtapp',
    storageBucket: 'dictojtapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdKpt0XeQIyLof5KRj8tHq62tks4hkEeU',
    appId: '1:70017366922:ios:93c16895a1c9533bcca673',
    messagingSenderId: '70017366922',
    projectId: 'dictojtapp',
    storageBucket: 'dictojtapp.firebasestorage.app',
    iosBundleId: 'com.example.dictojtt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdKpt0XeQIyLof5KRj8tHq62tks4hkEeU',
    appId: '1:70017366922:ios:93c16895a1c9533bcca673',
    messagingSenderId: '70017366922',
    projectId: 'dictojtapp',
    storageBucket: 'dictojtapp.firebasestorage.app',
    iosBundleId: 'com.example.dictojtt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDol-mM_GALl7VPmjyAg5Ntw5adz9DA6w8',
    appId: '1:70017366922:web:1a8c7dfcfe2bc242cca673',
    messagingSenderId: '70017366922',
    projectId: 'dictojtapp',
    authDomain: 'dictojtapp.firebaseapp.com',
    storageBucket: 'dictojtapp.firebasestorage.app',
    measurementId: 'G-TBE3X52CE4',
  );

}